version: '3.8'
services:
  database:
    image: postgres
    container_name: database
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php
    restart: always
    volumes:
      - .:/app
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./public:/app/public
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      php:
        condition: service_healthy
volumes:
  database:
